version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER} # from env

services:
  golang:
    build:
      context: ./golang # build golang dockerfile
    environment:
      - TZ=${TZ} # from env and refer to time zone
    privileged: true # as root
    volumes:
      - ${HOST_CODE_PATH}:/usr/src/code # from env ,mount local volume to container
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
    stdin_open: true # access std in from external(outside the container)
    tty: true # connect to pseudo terminal
    networks:
      - backend # using network which name as backend
    restart: always #if container is terminated,restart it

  etcd:
    build:
      context: ./etcd
    environment:
      - TZ=${TZ}
      - ALLOW_NONE_AUTHENTICATION=yes # without AUTHENTICATION
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379 # setting ETCD Client
    ports:
      - "${ETCD_PORT}:2389"
    networks:
      - backend
    restart: always

  mysql:
    build:
      context: ./mysql
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    privileged: true
    volumes:
      - ${HOST_DATA_PATH}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
    restart: always

  redis:
    build:
      context: ./redis
    environment:
      - TZ=${TZ}
    volumes:
      - ${HOST_DATA_PATH}/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend
    restart: always

  #running phpmyadmin
  mysql-manage:
    build:
      context: ./mysql-manger
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_MANAGE_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_MANAGE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_MANAGE_ROOT_PASSWORD}
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_MANAGE_CONNECT_HOST}
      - PMA_PORT=${MYSQL_MANAGE_CONNECT_PORT}
    ports:
      - "${MYSQL_MANAGE_PORT}:80"
    depends_on:
      - mysql
    networks:
      - backend
    restart: always

  redis-manage:
    build:
      context: ./redis-manager
    environment:
      - TZ=${TZ}
      - ADMIN_USER=${REDIS_MANAGE_USERNAME}
      - ADMIN_PASS=${REDIS_MANAGE_PASSWORD}
      - REDIS_1_HOST=${REDIS_MANAGE_CONNECT_HOST} # redis client host
      - REDIS_1_PORT=${REDIS_MANAGE_CONNECT_PORT} # redis client port
    ports:
      - "${REDIS_MANAGE_PORT}:80"
    depends_on:
      - redis
    networks:
      - backend
    restart: always

  etcd-manage:
    build:
      context: ./etcd-manager
    environment:
      - TZ=${TZ}
    ports:
      - "${ETCD_MANAGE_PORT}:8080"
    depends_on:
      - etcd
    networks:
      - backend
    restart: always

  prometheus:
    build:
      context: ./prometheus
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml # mount config yml file to container
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - backend
    restart: always

  grafana:
    build:
      context: ./grafana
    environment:
      - TZ=${TZ}
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - backend
    restart: always

  jaeger:
    build:
      context: ./jaeger
    environment:
      - TZ=${TZ}
    ports:
      - "${JAEGER_PORT}:16686"
    networks:
      - backend
    restart: always

  dtm:
    build:
      context: ./dtm
    environment:
      - TZ=${TZ}
    entrypoint: # setting dtm entrypoint
      - "/app/dtm/dtm"
      - "-c=/app/dtm/configs/config.yaml"
    privileged: true
    volumes:
      - ./dtm/config.yml:/app/dtm/configs/config.yaml # mount to container
    ports:
      - "${DTM_HTTP_PORT}:36789"
      - "${DTM_GRPC_PORT}:36790"
    networks:
      - backend
    restart: always

