Name: Product
Host: 0.0.0.0
Port: 8001

Mysql:
  DataSource: root:admin@tcp(mysql:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FHong_Kong

CacheRedis:
  - Host: Redis:6359
    Type: node
    Pass:

#set jwt auth
Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

#RPC Service
ProductRPC:
  Etcd:
    Hosts:
      - etcd:2379
    Key: product.rpc


Prometheus:
  Host: 0.0.0.0
  Port: 9081
  Path: /metrics

Telemetry:
  Name: product.api
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger