// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package server

import (
	"context"

	"mall/service/product/rpc/internal/logic"
	"mall/service/product/rpc/internal/svc"
	"mall/service/product/rpc/types/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) Create(ctx context.Context, in *product.CreateRequest) (*product.CreateResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *ProductServer) Update(ctx context.Context, in *product.UpdateRequest) (*product.UpdateResponse, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *ProductServer) Delete(ctx context.Context, in *product.DeleteRequest) (*product.DeleteResponse, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *ProductServer) Detail(ctx context.Context, in *product.DetailRequest) (*product.DetailResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}

// DTM function
func (s *ProductServer) DecrStock(ctx context.Context, in *product.DetailRequest) (*product.DecrStockResponse, error) {
	l := logic.NewDecrStockLogic(ctx, s.svcCtx)
	return l.DecrStock(in)
}

func (s *ProductServer) DecrStockRevert(ctx context.Context, in *product.DetailRequest) (*product.DetailResponse, error) {
	l := logic.NewDecrStockRevertLogic(ctx, s.svcCtx)
	return l.DecrStockRevert(in)
}
